ARM: EXYNOS4: Fix build break with CONFIG_PM disabled
This fixes following build error with CONFIG_PM_SLEEP and CONFIG_PM_RUNTIME
disabled:

arch/arm/mach-exynos/built-in.o: In function `exynos4_l2x0_cache_init':
/home/snawrocki/linux/media_tree/arch/arm/mach-exynos/common.c:400: undefined reference to `l2x0_regs_phys'
/home/snawrocki/linux/media_tree/arch/arm/mach-exynos/common.c:400: undefined reference to `l2x0_regs_phys'

Signed-off-by: Sylwester Nawrocki <s.nawrocki@samsung.com>
---

I'm not sure if it is a correct fix. Something similar would also need to
be done for Exynos5. I would update the patch accordingly if this approach
isn't wrong.